name: Auto deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }} #hostname of server
          password: ${{ secrets.PASSWORD }} #password login to server
          port: ${{ secrets.PORT }} #port of server - often port is 22
          script: | # run with multiple script
            cd ~/server/test-cicd
            cd test-cicd
            git pull
            printf "${{ secrets.ENV }}" > .env.production
            npm i
