name: Auto deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Check SSH connection
        run: ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} echo "SSH connection successful"
      
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/server/test-cicd
            git pull
            printf "${{ secrets.ENV }}" > .env.production
            npm i
